export const ID_INFORMATION_LIST_REQUEST = "ID_INFORMATION_LIST_REQUEST";
export const ID_INFORMATION_LIST_SUCCESS = "ID_INFORMATION_LIST_SUCCESS";
export const ID_INFORMATION_LIST_FAIL = "ID_INFORMATION_LIST_FAIL";

export const ID_INFORMATION_LIST_BY_USERID_REQUEST =
  "ID_INFORMATION_LIST_BY_USERID_REQUEST";
export const ID_INFORMATION_LIST_BY_USERID_SUCCESS =
  "ID_INFORMATION_LIST_BY_USERID_SUCCESS";
export const ID_INFORMATION_LIST_BY_USERID_FAIL =
  "ID_INFORMATION_LIST_BY_USERID_FAIL";

export const ID_INFORMATION_ADD_REQUEST = "ID_INFORMATION_ADD_REQUEST";
export const ID_INFORMATION_ADD_SUCCESS = "ID_INFORMATION_ADD_SUCCESS";
export const ID_INFORMATION_ADD_FAIL = "ID_INFORMATION_ADD_FAIL";
export const ID_INFORMATION_ADD_RESET = "ID_INFORMATION_ADD_RESET";

export const ID_INFORMATION_UPDATE_REQUEST = "ID_INFORMATION_UPDATE_REQUEST";
export const ID_INFORMATION_UPDATE_SUCCESS = "ID_INFORMATION_UPDATE_SUCCESS";
export const ID_INFORMATION_UPDATE_FAIL = "ID_INFORMATION_UPDATE_FAIL";
export const ID_INFORMATION_UPDATE_RESET = "ID_INFORMATION_UPDATE_RESET";

export const ID_INFORMATION_DETAILS_REQUEST = "ID_INFORMATION_DETAILS_REQUEST";
export const ID_INFORMATION_DETAILS_SUCCESS = "ID_INFORMATION_DETAILS_SUCCESS";
export const ID_INFORMATION_DETAILS_FAIL = "ID_INFORMATION_DETAILS_FAIL";

export const ID_INFORMATION_DELETE_REQUEST = "ID_INFORMATION_DELETE_REQUEST";
export const ID_INFORMATION_DELETE_SUCCESS = "ID_INFORMATION_DELETE_SUCCESS";
export const ID_INFORMATION_DELETE_FAIL = "ID_INFORMATION_DELETE_FAIL";
export const ID_INFORMATION_DELETE_RESET = "ID_INFORMATION_DELETE_RESET";
