export const LICENSE_LIST_REQUEST = "LICENSE_LIST_REQUEST";
export const LICENSE_LIST_SUCCESS = "LICENSE_LIST_SUCCESS";
export const LICENSE_LIST_FAIL = "LICENSE_LIST_FAIL";

export const LICENSE_LIST_BY_USERID_REQUEST = "LICENSE_LIST_BY_USERID_REQUEST";
export const LICENSE_LIST_BY_USERID_SUCCESS = "LICENSE_LIST_BY_USERID_SUCCESS";
export const LICENSE_LIST_BY_USERID_FAIL = "LICENSE_LIST_BY_USERID_FAIL";

export const LICENSE_ADD_REQUEST = "LICENSE_ADD_REQUEST";
export const LICENSE_ADD_SUCCESS = "LICENSE_ADD_SUCCESS";
export const LICENSE_ADD_FAIL = "LICENSE_ADD_FAIL";
export const LICENSE_ADD_RESET = "LICENSE_ADD_RESET";

export const LICENSE_UPDATE_REQUEST = "LICENSE_UPDATE_REQUEST";
export const LICENSE_UPDATE_SUCCESS = "LICENSE_UPDATE_SUCCESS";
export const LICENSE_UPDATE_FAIL = "LICENSE_UPDATE_FAIL";
export const LICENSE_UPDATE_RESET = "LICENSE_UPDATE_RESET";

export const LICENSE_DETAILS_REQUEST = "LICENSE_DETAILS_REQUEST";
export const LICENSE_DETAILS_SUCCESS = "LICENSE_DETAILS_SUCCESS";
export const LICENSE_DETAILS_FAIL = "LICENSE_DETAILS_FAIL";

export const LICENSE_DELETE_REQUEST = "LICENSE_DELETE_REQUEST";
export const LICENSE_DELETE_SUCCESS = "LICENSE_DELETE_SUCCESS";
export const LICENSE_DELETE_FAIL = "LICENSE_DELETE_FAIL";
export const LICENSE_DELETE_RESET = "LICENSE_DELETE_RESET";
