export const PILOT_ADD_REQUEST = "PILOT_ADD_REQUEST";
export const PILOT_ADD_SUCCESS = "PILOT_ADD_SUCCESS";
export const PILOT_ADD_FAIL = "PILOT_ADD_FAIL";
export const PILOT_ADD_RESET = "PILOT_ADD_RESET";
