export const RIDE_LIST_REQUEST = "RIDE_LIST_REQUEST";
export const RIDE_LIST_SUCCESS = "RIDE_LIST_SUCCESS";
export const RIDE_LIST_FAIL = "RIDE_LIST_FAIL";

export const RIDE_LIST_BY_USERID_REQUEST = "RIDE_LIST_BY_USERID_REQUEST";
export const RIDE_LIST_BY_USERID_SUCCESS = "RIDE_LIST_BY_USERID_SUCCESS";
export const RIDE_LIST_BY_USERID_FAIL = "RIDE_LIST_BY_USERID_FAIL";

export const RIDE_ADD_REQUEST = "RIDE_ADD_REQUEST";
export const RIDE_ADD_SUCCESS = "RIDE_ADD_SUCCESS";
export const RIDE_ADD_FAIL = "RIDE_ADD_FAIL";
export const RIDE_ADD_RESET = "RIDE_ADD_RESET";

export const RIDE_UPDATE_REQUEST = "RIDE_UPDATE_REQUEST";
export const RIDE_UPDATE_SUCCESS = "RIDE_UPDATE_SUCCESS";
export const RIDE_UPDATE_FAIL = "RIDE_UPDATE_FAIL";
export const RIDE_UPDATE_RESET = "RIDE_UPDATE_RESET";

export const RIDE_DETAILS_REQUEST = "RIDE_DETAILS_REQUEST";
export const RIDE_DETAILS_SUCCESS = "RIDE_DETAILS_SUCCESS";
export const RIDE_DETAILS_FAIL = "RIDE_DETAILS_FAIL";

export const RIDE_DELETE_REQUEST = "RIDE_DELETE_REQUEST";
export const RIDE_DELETE_SUCCESS = "RIDE_DELETE_SUCCESS";
export const RIDE_DELETE_FAIL = "RIDE_DELETE_FAIL";
export const RIDE_DELETE_RESET = "RIDE_DELETE_RESET";
