export const VEHICLE_LIST_REQUEST = "VEHICLE_LIST_REQUEST";
export const VEHICLE_LIST_SUCCESS = "VEHICLE_LIST_SUCCESS";
export const VEHICLE_LIST_FAIL = "VEHICLE_LIST_FAIL";

export const VEHICLE_LIST_BY_USERID_REQUEST = "VEHICLE_LIST_BY_USERID_REQUEST";
export const VEHICLE_LIST_BY_USERID_SUCCESS = "VEHICLE_LIST_BY_USERID_SUCCESS";
export const VEHICLE_LIST_BY_USERID_FAIL = "VEHICLE_LIST_BY_USERID_FAIL";

export const VEHICLE_ADD_REQUEST = "VEHICLE_ADD_REQUEST";
export const VEHICLE_ADD_SUCCESS = "VEHICLE_ADD_SUCCESS";
export const VEHICLE_ADD_FAIL = "VEHICLE_ADD_FAIL";
export const VEHICLE_ADD_RESET = "VEHICLE_ADD_RESET";

export const VEHICLE_UPDATE_REQUEST = "VEHICLE_UPDATE_REQUEST";
export const VEHICLE_UPDATE_SUCCESS = "VEHICLE_UPDATE_SUCCESS";
export const VEHICLE_UPDATE_FAIL = "VEHICLE_UPDATE_FAIL";
export const VEHICLE_UPDATE_RESET = "VEHICLE_UPDATE_RESET";

export const VEHICLE_DETAILS_REQUEST = "VEHICLE_DETAILS_REQUEST";
export const VEHICLE_DETAILS_SUCCESS = "VEHICLE_DETAILS_SUCCESS";
export const VEHICLE_DETAILS_FAIL = "VEHICLE_DETAILS_FAIL";

export const VEHICLE_DELETE_REQUEST = "VEHICLE_DELETE_REQUEST";
export const VEHICLE_DELETE_SUCCESS = "VEHICLE_DELETE_SUCCESS";
export const VEHICLE_DELETE_FAIL = "VEHICLE_DELETE_FAIL";
export const VEHICLE_DELETE_RESET = "VEHICLE_DELETE_RESET";
